name: build-test-release

on:
  pull_request: { branches: [ main, master ] }
  push:         { branches: [ main, master ] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install / Build / Test (skip if not applicable)
        shell: bash
        run: |
          if [ -f package.json ]; then
            if [ -f package-lock.json ]; then
              npm ci
            else
              npm install
            fi
            npm run -s build || echo "No build script, continue."
            npm test --silent || echo "No tests, continue."
          else
            echo "No package.json found, skipping Node steps."
          fi
